repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5
          - "prettier-plugin-solidity@1.3.1"
  - repo: local
    hooks:
      - id: solhint-contract
        name: solhint-contract
        entry: npm run solhint:contract
        always_run: true
        language: system
      - id: solhint-test
        name: solhint-test
        entry: npm run solhint:test
        always_run: true
        language: system
      - id: solhint-script
        name: solhint-script
        entry: npm run solhint:script
        always_run: true
        language: system
exclude: |
  (?x)^(
      package-lock.json|
      package.json|
      foundry.toml|
      .solhint.json|
      .pre-commit-config.yaml|
      .solhintignore|
      .idea|
      .gitmodules|
      .gitignore|
      README.md|
      smart-contracts-build.yml |
  )$
