repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8" # Use the sha or tag you want to point at
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5
          - "prettier-plugin-solidity@1.3.1"
  - repo: local
    hooks:
      - id: solhint
        name: solhint
        entry: npm run solhint:pre-commit
        always_run: true
        language: system
exclude: |
  (?x)^(
      package-lock.json|
      package.json|
      foundry.toml|
      .solhint.json|
      .pre-commit-config.yaml|
      .solhintignore|
      .idea|
      .gitmodules|
      README.md|
  )$
