name: Smart contracts build

on:
    workflow_call:
        secrets:
            ETHEREUM_PROVIDER_URL:
                required: true
            ARBITRUM_PROVIDER_URL:
                required: true
            BASE_PROVIDER_URL:
                required: true

        inputs:
            node-version:
                description: "Node.js version"
                type: string
                default: 20.17.0
                required: false

            build-enabled:
                description: "Enable build"
                type: boolean
                default: true
                required: false

            sizes-enabled:
                description: "Enable Forge sizes check"
                type: boolean
                default: true
                required: false

            test-enabled:
                description: "Enable Forge tests"
                type: boolean
                default: true
                required: false

            build-options:
                description: "Extra options in Forge build command"
                type: string
                default: ""
                required: false

            sizes-options:
                description: "Extra options in Forge sizes check command"
                type: string
                default: ""
                required: false

            test-options:
                description: "Extra options in Forge test command"
                type: string
                default: ""
                required: false

            solhint-enabled:
                description: "Enable Solhint linting"
                type: boolean
                default: true
                required: false

            prettier-enabled:
                description: "Enable Prettier formatting"
                type: boolean
                default: true
                required: false

env:
    FOUNDRY_PROFILE: ci

jobs:
    smart-contracts:
        runs-on:
            group: foundry-build

        steps:
            - name: Checkout
              # from tag: v4.2.2
              uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
              with:
                  submodules: recursive

            - name: Setup Node.js
              # from tag: v4.2.0
              uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a
              with:
                  node-version: ${{ inputs.node-version }}

            - name: Setup node_modules cache
              # from tag: v4.2.2
              uses: actions/cache@d4323d4df104b026a6aa633fdb11d772146be0bf
              with:
                  path: "**/node_modules"
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

            - name: Setup Foundry
              # from tag: v1.2.0-ipor
              uses: IPOR-Labs/foundry-toolchain@18ecb60c02f281f6906d3349abfe450d295be7a8
              with:
                  version: nightly-03ea54c63e33e3175a6f44d8cfe3718bd6c962ba

            - name: Install
              run: npm install

            - name: Forge build
              if: inputs.build-enabled
              run: |
                  forge --version
                  forge build ${{ inputs.build-options }}
              id: build

            - name: Forge sizes
              if: inputs.sizes-enabled
              run: |
                  forge build --sizes ${{ inputs.sizes-options }}
              id: sizes

            - name: Forge tests
              if: inputs.test-enabled
              env:
                  ETHEREUM_PROVIDER_URL: ${{ secrets.ETHEREUM_PROVIDER_URL }}
                  ARBITRUM_PROVIDER_URL: ${{ secrets.ARBITRUM_PROVIDER_URL }}
                  BASE_PROVIDER_URL: ${{ secrets.BASE_PROVIDER_URL }}
                  TAC_PROVIDER_URL: ${{ secrets.TAC_PROVIDER_URL }}
              run: |
                  forge test ${{ inputs.test-options }} -vvv --ffi
              id: test

            - name: Solhit
              if: inputs.solhint-enabled
              run: |
                  npm run solhint:all
              id: solhint

            - name: Prettier
              if: inputs.prettier-enabled
              run: |
                  npm run prettier:all
              id: prettier
