name: Smart contracts build

on:
  workflow_call:
    secrets:
      ETHEREUM_PROVIDER_URL:
        required: true
      ARBITRUM_PROVIDER_URL:
        required: true

    inputs:

      node-version:
        description: "NodeJS version"
        type: string
        default: 20.11.1
        required: false

      build-enabled:
        description: "Enable build"
        type: boolean
        default: true
        required: false

      test-enabled:
        description: "Enable Forge tests"
        type: boolean
        default: true
        required: false

      build-options:
        description: "Extra options in Forge build command"
        type: string
        default: ""
        required: false

      test-options:
        description: "Extra options in Forge test command"
        type: string
        default: ""
        required: false

      solhint-enabled:
        description: "Enable Solhint linting"
        type: boolean
        default: true
        required: false

      prettier-enabled:
        description: "Enable Prettier formatting"
        type: boolean
        default: true
        required: false

env:
  FOUNDRY_PROFILE: ci

jobs:
  foundry-tests:
    runs-on:
      group: foundry-build

    steps:
      - name: Checkout
        # from tag: v4.1.4
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b
        with:
          submodules: recursive

      - name: Setup node
        # from tag: v4.0.2
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8
        with:
          node-version: ${{ inputs.node-version }}

      - name: Set up node_modules cache
        # from tag: v4.0.2
        uses: actions/cache@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install
        run: npm install

      - name: Install Foundry
        # TODO: update foundry-toolchain and user nightly version
        # from tag: v1.0.10-ipor-v1
        uses: IPOR-Labs/foundry-toolchain@d9760eeeaf64fdac14339e530358e15925d2997c
        with:
          version: nightly-ba6c85112f4c34fc8eb081645bad278f48343ec4

      - name: Run Forge build
        if: inputs.build-enabled
        run: |
          forge --version
          forge build ${{ inputs.build-options }}
        id: build

      - name: Run Forge tests
        if: inputs.test-enabled
        env:
          ETHEREUM_PROVIDER_URL: ${{ secrets.ETHEREUM_PROVIDER_URL }}
          ARBITRUM_PROVIDER_URL: ${{ secrets.ARBITRUM_PROVIDER_URL }}
        run: |
          forge test ${{ inputs.test-options }} -vvv
        id: test

      - name: Run Solhit
        if: inputs.solhint-enabled
        run: |
          npm run solhint:all
        id: solhint

      - name: Run Prettier
        if: inputs.prettier-enabled
        run: |
          npm run prettier:all
        id: prettier
